### ISSUE TITLE
В локальном чате !clantag! вместо названия клана

### ISSUE THREAD

**Issue by MorokMC** [Ilya-Evtukhov/UralClans2-Extension#2]
На сервере использую EssentialsChat, в частности локальный чат на 100 блоков.
Если игрок пишет в локальный чат, то у администрации вместо показа названия клана пишется !clantag!
![2015-08-25_11 52 35](https://cloud.githubusercontent.com/assets/2644698/9461515/4f8be3da-4b20-11e5-9968-1ea9dc33aa84.png)

**Comment by MorokMC** [comment]
Данная проблема решается, если в файле **EventListener.java** убрать в одном месте приоритет

![default](https://cloud.githubusercontent.com/assets/2644698/9463606/c979c320-4b2e-11e5-9ac2-6e4a80b2fa85.png)

**Comment by Ilya-Evtukhov** [comment]
priority = EventPriority.LOW будет лучше

**Comment by Ilya-Evtukhov** [comment]
В след. обновлении будет исправлено)

**Comment by Dimatert9** [comment]
Добавь ещё /c tag чтобы в чате можно было свой тег делать

**Comment by Ilya-Evtukhov** [comment]
Структуру плагина менять нужно будет, я конечно буду пробовать, но гарантий вообще никаких...

**Comment by Dimatert9** [comment]
в первой версии плагина было это, мож это поможет както
